version: '2'
services:

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch
    ports:
      - "9200:9200" # Rest API
      - "9600:9600" # Performance analyze
    environment:
      DISABLE_SECURITY_PLUGIN: true
      discovery.type: single-node
      plugins.ml_commons.only_run_on_ml_node: false
      plugins.ml_commons.model_auto_redeploy.enable: true

    networks:
      - opensearch-net
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true 
    networks:
      - opensearch-net


volumes:
  opensearch-data:

networks:
  opensearch-net: